// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBls6ADA_993NXHSqzaviQgrpner7j4_CA',
    appId: '1:41410537530:web:41133b30dfa75fce40ed03',
    messagingSenderId: '41410537530',
    projectId: 'voyage-c9aef',
    authDomain: 'voyage-c9aef.firebaseapp.com',
    storageBucket: 'voyage-c9aef.appspot.com',
    measurementId: 'G-FL20H4R8MQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_axl8wEk3ma3yEsRcOXlox75cHE63pJM',
    appId: '1:41410537530:android:9c3fb7c058fde0de40ed03',
    messagingSenderId: '41410537530',
    projectId: 'voyage-c9aef',
    storageBucket: 'voyage-c9aef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF7XxF2X1Jbk759THSkf8Kb7RBVgXt85w',
    appId: '1:41410537530:ios:e12517a987a7886b40ed03',
    messagingSenderId: '41410537530',
    projectId: 'voyage-c9aef',
    storageBucket: 'voyage-c9aef.appspot.com',
    iosClientId: '41410537530-npso0b0872udrc7t69jpjuhngnfc7has.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
